FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

RUN npm install -g @ionic/cli

RUN npm install -g serve

RUN sudo apt update

RUN sudo apt install android-sdk -y

RUN sudo apt install openjdk-17-jdk -y

RUN npm install -g npm@10.8.0
